# yaml-language-server: $schema=https://raw.githubusercontent.com/runkids/skillshare/main/schemas/config.schema.json
sources:
  skills: ~/.config/skillshare/skills
  agents: ~/.config/skillshare/agents
mode: symlink
targets:
  cline:
    skills:
      path: ~/.cline/skills
  crush:
    skills:
      path: ~/.config/crush/skills
  forgecode:
    skills:
      path: ~/.config/forge/skills
  goose:
    skills:
      path: ~/.config/goose/skills
  opencode:
    skills:
      path: ~/.config/opencode/skills
  universal:
    skills:
      path: ~/.agents/skills
extras:
  - name: commands
    targets:
      - path: ~/.config/opencode/commands
        mode: symlink
      - path: ~/Documents/Cline/Workflows
        mode: symlink
ignore:
  - "**/.DS_Store"
  - "**/.git/**"
audit:
  block_threshold: CRITICAL
