repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: detect-private-key
      - id: check-yaml
      - id: sort-simple-yaml
      - id: check-json
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: pretty-format-json
        args: ["--autofix"]
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
  - repo: local
    hooks:
      # Toml
      - id: taplo-format
        alias: taplo
        name: taplo-format
        description: Format TOML files
        entry: taplo format
        language: python
        types: [toml]
        additional_dependencies: [taplo]
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.13.1-1
    hooks:
      - id: shfmt
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.5.2
    hooks:
      - id: stylua
  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
  - repo: https://github.com/editorconfig-checker/editorconfig-checker
    rev: v3.7.0
    hooks:
      - id: editorconfig-checker
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/lunarmodules/luacheck
    rev: v1.2.0
    hooks:
      - id: luacheck
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0
    hooks:
      - id: pre-commit-update
