# selected profile, required
profile: main
# repository to sync the settings with, required
repository:
  # repository's type, required (dummy: no sync)
  type: git
  url: git@github.com:chadsr/vscode-settings.git
  branch: main

# how to run commands before and after events at https://github.com/zokugun/vscode-sync-settings/blob/master/docs/hooks.md
hooks:
  post-upload: notify-send -a VSCodium -u low -t 10000 "VSCodium settings have been uploaded"
  post-download: notify-send -a VSCodium -u low -t 10000 "VSCodium settings have been downloaded"
